twilio:
  accountId: AC0bfca3da39e9d00b8a3e03991af00000
  accountToken: e3511f257424cea8dadfddcd42800000
  localDomain:  signal.domain.com
  numbers:
    - "+12565769630" # Change this to your number from Twilio

backupService:
  userAuthenticationTokenSharedSecret: bd5ee839bfa83dc1f60af05d7db00000 # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`

storageService:
  userAuthenticationTokenSharedSecret: cffe9b783677f8ee3dfb485eef000000 # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`

push:
  queueSize: 200

turn: # Coturn server configuration
  secret: secret # You will need the same config with the secret in turnserver.conf
  uris:
    - stun:127.0.0.1:3478 # If you change the port in turnserver.conf, change this too
    - stun:127.0.0.1:5349 # If you change the port in turnserver.conf, change this too
    - turn:127.0.0.1:5349?transport=udp # If you change the port in turnserver.conf, change this too
    - turn:127.0.0.1:3478?transport=udp # If you change the port in turnserver.conf, change this too

cache: # redis server for cache cluster
  url: redis://127.0.0.1:6379/cache # change to your redis server
  #replicaUrls:
  #  -  redis://127.0.0.1:6379/cacheReplica # change to your redis server

directory:
  redis: # Redis server configuration for directory cluster
    url: redis://127.0.0.1:6379/directory
    #replicaUrls:
    #  -  redis://127.0.0.1:6379/directoryReplica
  client: # Configuration for interfacing with Contact Discovery Service cluster
    userAuthenticationTokenSharedSecret: adbe341ca076657e34e4e29e3bf00000 # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`
    userAuthenticationTokenUserIdSecret: e9cbgd33d99073f48c7acc015f900000 # Generate it with `head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'`
  sqs:
    accessKey:    AKIAQ565H442HJM00000 # Change this to your AWS IAM Access Key
    accessSecret: cvjr4YVENZW/samH3G33ntliGVKM3oVYJh300000 # Change this to your AWS IAM Secret
    queueUrl:     https://sqs.eu-west-3.amazonaws.com/044351627060/signal.fifo # Change this to your AWS SQS (FIFO) URL
  server: # You can change the certificate with your own certificate
    replicationUrl: http://127.0.0.1:9090 # CDS replication endpoint base url
    replicationPassword: mypassword # CDS replication endpoint password
    replicationCaCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIF7zCCA9egAwIBAgIUUme0O2hOX+OWLwfKyIzgMFl4sjcwDQYJKoZIhvc00000
      BQAwgYYxCzAJBgNVBAYTAklEMRQwEgYDVQQIDAtES0kgSmFrYXJ0YTEQMA4GA1UE
      BwwHSmFrYXJ0YTEPMA0GA1UECgwGVGVsa29tMQwwCgYDVQQLDANEZXYxEDAOBgNV
      BAMMB2NoYXRhcHAxHjAcBgkqhkiG9w0BCQEWD2RldkBleGFtcGxlLmNvbTAeFw0y
      MDAxMTAwODEzMzFaFw0yMTAxMDkwODEzMzFaMIGGMQswCQYDVQQGEwJJRDEUMBIG
      A1UECAwLREtJIEpha2FydGExEDAOBgNVBAcMB0pha2FydGExDzANBgNVBAoMBlRl
      bGtvbTEMMAoGA1UECwwDRGV2MRAwDgYDVQQDDAdjaGF0YXBwMR4wHAYJKoZIhvcN
      AQkBFg9kZXZAZXhhbXBsZS5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
      AoICAQCzGVGK0BM47gmPKE5DlNPuXIA/Jx+DdBMUhyt4AxxrtPBjbruVO05OMjcT
      qAXO+DatSQZT/K2/0oQACevrKIkBhXJwe4iUjWNb7nymntG8NKoQbByksYMTLXlj
      OrkPB9fOiGIFlNCZkFDdTkvMrjacjJvXtOMJMkc2UwUtNQ3ss5XLzVFx5J21Q3oo
      Ee1qnGJTUnmvOdCJHJzr7z7VdS6xeN6SOfmRPUi8LdKSbRG8KUcMPFMfMH1yvj6d
      eoTMPEuYq0Pm8j6yR7j+gHaRprlPAAPy9T7N5mN9Pdc7wDLo1qOr7TJ0PgLD641L
      o7uvS0u21tX2g/cR7cBzaEMV0XOJqh3LjHDlbJ1yUXXFSOLcLnXgmmrHL2HqTslF
      DDIh0ns8xG6iaI2CG7xHTJBfFhO0tA1yyUbivSQBRmJNozAPFTfOHtWNCesMJPFC
      x4FPp1iRQwBhAsJ3D80Fd+RNJH7WxP/ffEHPz2AbVqSSPdFjkI5xSqQLR5/k3bMa
      xGu7w0qQ7ifFYOEtETe+Xo1cUYbnheFPUoExxoRcWWl/42uTGsZazTlUo+LWH0yb
      xEB+MWmPREYqeCaoRIXV5UTsDlXjuQpRnIDl1xgdUkFTN6Trfn0eAUuRNM0bbQNL
      hDwCCLU4c2oY1mGgcXklxzOZIk5KQMFSMlOkVGhM6R2MmL1UWQIDAQABo1MwUTAd
      BgNVHQ4EFgQUBe0rUnGIOfQFvFcSzKB6HQhbCVYwHwYDVR0jBBgwFoAUBe0rUnGI
      OfQFvFcSzKB6HQhbCVYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AgEAmnb/xuo8AcqzL+cVnu+SSxHHJPPhMM7Bnm8ChFnw/CqeTRbxwa5Po7tj47CF
      ZH9NPpi3UEYGhAeyTcIPpa7mcgaIDoOrYA7Ku6BT2/KhlQu6vVg5xw3QBrnfplm+
      9VOnfKKoH7nD2lrW7rVZ/EZGzeChtI0AzCAlcnBQCnXziY5++LkWCzPmofHq+moP
      OAHyLMb3pUyPdCgTETLrrgNixrlb5s/rqTrwNe3XUo1YrPMTYzCN5mrCqQtOsvFp
      2L+y8RlfQ+AFJeQDCC6eUFYfK3Ls6qz7agm19EmyXO642M5eOdT4tobgt24YsnGx
      TupofOEbBU9F31LELSwe3bAu5N8RZvhay5C5u9ZrrUNlp1pr1Ljy0r51SmckmyY7
      4g8IT28E3cZhyFUsqwihxlwf9oHhxAzxOTVWiSobibc8r0q3hp3PutQFyPLRrfMf
      hDPTpUPm8v1rFRxNWXpe3w92y/iiJ53S4CWVmBIW9iKGqOyj7l2VEqe7KGKVO3Ma
      Z5b5jQMf6d2N1Qk2tt8YnL6EbT0mOJedhAfnkJl71UZzK7Lz1kLT+1MnlF+gazol
      vJiET6YNSW7sU/GNafapLfIqXU2wCfOFcrLEsW+DOEM2MLcY48ypPDcnwsl6OG+K
      qXeFHFld6v6s6pIGmc50pflU4qSJHAASDsUxw08xKxXnTEg=
      -----END CERTIFICATE-----
messageCache: # redis server for message store cache
  redis:
    url: redis://127.0.0.1:6379/messageCache # change to your redis server
    replicaUrls:
      -  redis://127.0.0.1:6379/messageCacheReplica # change to your redis server

awsAttachments: # aws s3 configuration
  accessKey: AKIAQ565H442DES00000 # Change this to your AWS IAM Access Key
  accessSecret: YmpZCxz2lzgemvmLTa2uC38IG2ADBFztm5l00000 # Change this to your AWS IAM Secret
  bucket: signal-01-attachments # Change this to your bucket's name
  region: eu-west-3 # Change this to your bucket's region

cdn: # aws cdn configuration
  accessKey: AKIAQ565H242DES00000 # Change this to your AWS IAM Access Key
  accessSecret: YmpZCxf2lzgembmLTa2uC38IG2ADBFztm5l00000 # Change this to your AWS IAM Secret
  bucket: signal-01-attachments # Change this to your bucket's name
  region: eu-west-3 # Change this to your bucket's region

# openssl genrsa -out private_key_rsa_4096_pkcs1.pem 4096
# openssl pkcs8 -topk8 -in private_key_rsa_4096_pkcs1.pem -inform pem -out private_key_rsa_4096_pkcs8-exported.pem -outform pem -nocrypt
#add \n to the certificate: awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}'  private_key_rsa_4096_pkcs8-exported.pem
gcpAttachments: # gcp storage configuration
  domain: domain.com
  email: dummy@dummy.com
  maxSizeInBytes: 1000000
  pathPrefix: /
  rsaSigningKey: "-----BEGIN PRIVATE KEY-----\n00000wIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQC+Vc953tkvuVNs\novyzyJndbn7nNZ1b4pb109I9nQowGL9B6MXiG4WQJ6S92b4gL9e891eXSrfJHvCB\nZb4199tCVRXZ9k4aYlzQcV2OUWEo0Ym5rcpnTx1c9mKJSCbaNyD7HWeIfUvPbM0p\nGErvIrjBiKFTS1oagoa4pZVjqMKU42lF3FdLT3DzVYXhKrYH3qwdIgeUavCSjBSx\nQfuYSvFmHW7ZezLmqmonDe5N6CzvBLlsUCcWWl5/+aPosFWzCsAyiKE8/OZJ08s4\nGFbwivJIAs2WZif32ZlmeZ7962hkxDgfh1LmaU5Q0AvGB2SjQJaK4fNln0zKCMVI\n3TSnFSTT6AzL6+4kilELy+JVUdIt+IZ1SnkZ3Xd4LHMw+GDIlzpLB4G0tyQBccIg\na5dCaQV53/xP2NPSKmnR0+DemV3cTvXM8SY03YOJchRSWgN1zATTQKhI6NbwHs3j\nfbUWVfreNvPREDjIku3SsSYSnG+WPsPIy3QHJX3QzvdARcGX0f23shbG5f1KDxWe\nQDDpqpmAa48N2BLya3eL2QPxq/1o+bK00Nm+Clb+mGWmJATbZD89jNBuEA2IospL\ndORsUAXIjWV3XLKMeRszC9PCDt6zQBXNQSUCPtylGsdZi/4i3E19+2IxGb5QbODO\nlwwDZ0BgC/KAgs+e8X2sBE2rS/F4zQIDAQABAoICAQCztuJH+Bqp7RrQILTqLCbb\n5VD9jqod8D0JsA97DaRo9XThDqCJdeMO0d/DQq06RvI1AnY569rMk+ISy7ZlzrnA\nUAZp3x6v2uA4EFJ95mkO2YppP6c1FIZtGFbBuNa2hAcoFAOF5IiIOfsdKkrWsLoy\nQofQ1f0lusjp367Ggrn3SyJDTGFAQqormDzo9iMaGy339AGkKbUtKgb/t4WPrnNw\nL6pSvvi4w3+nkIfKF8cViChsFOJTQNCplVUmiBjjDOucy1Uy+LeYTdo8BP9R8GAD\njmH/+EUUyOkG0R9GMdhIDN3RJz0nQZcoxsfXG3PykTGTwPTIpzkiKlXdDsCAYn55\n1mssc0z26QXOXxa2DeZxncHSdFG39RY6QyGyQ/Uy7+w5LfBHGO/V/GujOlNI0u/U\nyuSS6I6KyYILdi3zF+9FzC80aycwLsYaKkMTP4birdFTp53X49IQLg6shUDC6cSY\nV+v7lK8GYtxRp3hq7vL5/FuUUNbCc5eW6wGr6EX5XC5U/g8jytMkETpO7/3MgHMj\nkfL0jU+bBj0VzqHd7r2PKDfph+I8Q405yqwbno+Q0+4ALhDSwQDwXN5nZPLPx9zd\nl9slfQDolTxlhw7J/qRJFbE1KTZztZsjsbz57gPOLkB8OCFoP6K1kfwJNcNyZJv/\nZmXm/9Tp5Z+AKEdTx1bHIQKCAQEA3rSl5a2WtdX/rl9Ggv+Ji6chgvaTxj/ABJc4\ntABgIGXCkNx1ugYBoAzvPqau5YvPOHIiUUGLWpUlLpeE/Vr7Zzd5lF4aWlHiSGNC\n0qbJdPV64BuHkNb2M6z1czYwcjSa/SHyidEnGXpAUIoG+d16pqcsPVmniBSFOFRl\n5Wn8Uf3868WuofW8Ryfdhdqgf2lGVFqBcaehIyXIonCcZnEoymz7jsGevRxRDWr2\nTRuJrOgdenorf+8LVfxkzcppT7RE4SH7xy183FAxpK/4P6HHn7N5zfb3ZOfiC1Nw\nazdOJpIKtyKj/0hkjetyxm0RlzOFZ9azZ/Y+WhtXYXfHJlkMSwKCAQEA2spJLdRa\nX6GS7e53mtfOrAGDz02muoW65aZ2vOHrI+1qu+j5Lv9sOZ+dYDZMEOSikVOT+Xuf\n+R1uwS5OGcR34FegEeciVOY4+9ThlI8A6jCI5HctsbdHujeOm6rZZudzEH9pbXB8\n5Ss0XkBK4n0FhY4HovDj5CEze8rncPtceccyO/UDX7PTIf2Se5mVyz5gIV83Pf3M\n5/m+IlJpjqSmwmOrKPVjF5LsdZuTO7Woi+PEgqllAjhMhm4aROVNhei1dpyF1+Jv\niIR3PpyvT1xlaaqYteMXiyiV3RxKHvc7w2gSBu47Yl3fNW61qfpsEfwXOwGAGWBv\nrDqfzHkKDDMwRwKCAQAlLQq0eHG8EOkJdqYSoA2Z3mBduEOayHGJUqUIhzeEsPf1\nrpeIYhBLY11cm/5+GwSQa50G62YTzOnUCT8N++4ToNMOzVag1SJs6wTwnR7sAz5r\nwqyypO+cWLbwcI9NwTJOJyiRkPRx8FJkH2Zit3IN98IOy7SHpsVGTfBkh3izRy69\nPNaV+qtfRWxZN9Gq8yvmUOViz5S6hUgktZ+mCiXBBMhJYFDbSKrPDpfm7z3gOy8Q\njuxMAt9ljyhUogFKaNFGs6GP8ivxqwFeeHF8TclBA3jFxQAvO/Yj5d3SR/0nuyFG\nyOWPa8o9VpxmOzbAgr02RETWieiGqiHAB3qbECpZAoIBAA+Uli+ATss+m1L8R2Is\nehg/p15M3lGsEkomV5BN2kvdrVsiVRRmthNIbZGbbEFLttP4irIafqLj2K5DGOa2\n2f6M3uZHemdnWal9WG8W2+7Rc/4pCoT8U0xMhohJW1/7nXMQT7auawZ61CjeFTcZ\nxhnjqmGNG/1z69Gl+mNOUyCM8ePZJ9tZ1/A0uYi5wDQQBhJ6UFnGyB/A5ixViBTT\nXti69kZdaygTm2koogx/fDgyCR1w6LOGxNRR5OcBGUsu7jU7IkDkbCLhpAg+ajGR\nl9s1fdh+CoArbLipOhIIcyYQNDBwKKRxoOKSNrebELUbKaBXFAM6ndk694Q9Hl0O\nDCMCggEBAJQCf9j9pt9wpcqitvlxvND9dVgy4/HGltsKOVvARyHTgdNiGllOF+Rv\nOIN+m9blK6L77iABlnGdccOwvj7VQN0LS0e2nTDbbiTYV0XC18tX86zIku8GEX0e\nlZX9A7s9P9LL7zXc2C2dtexwZhEeTxace4H8Sym22/9mHvXHlKF8MJMfxlhPVUSQ\nSJeakuuG8ctr8zHW7pYFCSwRjLPjVyMkLxf2jmLLpuKAWmrXEcCLip0i4fgRQjqy\nQHDUKcJCFaM24nFX75RPzXHAZ2D520rndTIOdHPumGCb1Y3eJz/UP/XhJ7+tqJcN\nnYPuhuYhpe3oa56QuiAr1CcJZ4w/ihE=\n-----END PRIVATE KEY-----\n"

pubsub: # redis server for pubsub cache
  url: redis://127.0.0.1:6379/cache # change to your redis server
  replicaUrls:
    -  redis://127.0.0.1:6379/cacheReplica # change to your redis server

remoteConfig: # remote configuration token
  authorizedTokens:
    - dummy

zkConfig: # zkgroup config, run using your build jar
  serverSecret: 00000usXOzS6zRWjvYtEs4p5IZdWhqeubGE+xmwQ1aV9pR8NJtsGU594ecDmtC4KA5ifp5NfrA8fhFXPODhKZ1VaRzAvpyX9NPmAVkJ/YU3xfVzhkJ81vkeyhOzdt6VNVPkrrjzQX++bRQuTX1OSidski1mZ+Re7OWppZAQamILdIJFFmFqgGv9j6pS1tbQUL4Bgqr3g9XVpBT3/oBNmzhaVyE3SvyNAqYXbkmp0rpKQhT+5nQQRcbg8w4XwIY84kcL7U5W5ZHNRYVDYfdx8TPNLfAT8nmfJDrHCejQQeRHZZR8BuPFSd4lk9gCeAJoV49rVhYM/rSGwt1krZDf1jaKAObjmOLh1JNAsZV8e6VLFQrM/tIwWp/ec1HEAC2t5ztABb1d3fZQlS+44hM6DzvMJFv6bPaDrDR8dF+Q4BpywUI9dkut/u1W/ih0Ca73le/uCZRTW1pmnsn33jCBS+lFhWKBw8WQm3Psp03WE4She3U05Y2XjgBiE0mOlleoPrH9JatjA04g00QlMWLn2jbpHsCCMlJwHkArIJGUUGnFPnenYOPFEM87SxxTPO0cFEoJdgIxeMVrNTgZ3xBsiYyxNcYElu2VL/+pRPFSak9njuIBtlK59MMujipiEONN6JY/CvtqwtCKAV9Sbe03ko4IWrQ6wmh67RRsG50ky1Q/FxJ8dAdMBLj0gQtUaAznLVc0+fWbFtM/7/kho+C/0VAgpUA8Arf3EdpHnnCfNcRtOMUiPexIeMHnrbHkIPTkTdH1rIgMl6/AsksjlSMVq7m3fX9w1axRiiDyiHxAbtA5iXScbyOHZMzr3h1SfsQ1/ore/fzeiykxlX+3XABoL0PJ6YM62VFq8Br2bl84fuOkR+tIf/GmeLvnoEY5oE75ki6F5yH3TQkBT1+6WgpqMJNHr7wivIsPp1l9vbnQAxhTkkMSfL05V3+1Z0uT61YCdzy2AJQD4s4siGRSghAWW1m+xQLrWti1/icPwFTpIvUxFFlV9ti+ar4IW3XxsF+D3oIH4wyYZFSHyvW1AAbGz1a7sgvK8VZ4EXRzGUjU3CXOLNC1Vk6g3yFhgfvxRN0nklSd4kmo1gpXpSRIi5JjMNZ1vzyOYZc1DWO0tqOwGgnv/8fl7/NYUVimDGVVkNrG+0osEgldnLCCbauewbluL1G8nT4RdGxpJIr1ohWU4
  serverPublic: FL6UWFYoHDxZCbc+ynTdYThKF7dTTljZeOAGITSY6WV6g+sf0lq2MDTiDTRCUxYufaNukewIIyUnAeQCsgkZRfg96CB+MMmGRUh8r1tQAGxs9Wu7ILyvFWeBF0cxlI1NwlzizQtVZOoN8hYYH78UTdJ5JUneJJqNYKV6UkSIuSasb7SiwSCV2csIJtq57BuW4vUbydPhF0bGkkivWiFZTg
  enabled: true

accountsDatabase: # database for account
  driverClass: org.postgresql.Driver
  user:        postgres
  password:    postgres
  url:         jdbc:postgresql://localhost:5432/signal-accounts

messageStore: # database for message
  driverClass: org.postgresql.Driver
  user:        postgres
  password:    postgres
  url:         jdbc:postgresql://localhost:5432/signal-messages

abuseDatabase: # database for abuse
  driverClass: org.postgresql.Driver
  user:        postgres
  password:    postgres
  url:         jdbc:postgresql://localhost:5432/signal-abuse

gcm: # firebase messaging
  senderId: 000000000 # your sender id
  apiKey: xxxxxxxxxxx # your api key

recaptcha: # google recaptcha v3
  secret: xxxxxxxxxxx # your recaptcha secret

accountDatabaseCrawler: # crawler for account database
  chunkSize:       1000
  chunkIntervalMs: 1000000

apn:
  pushCertificate: "-----BEGIN CERTIFICATE-----\r\nMIIFjzCCBHegAwIBAgIRfkSIVVtC9UIwDQYJKoZIhvcNAQEFBQAwgZYxCzAJBgNV\r\nBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3Js\r\nZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3\r\naWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw\r\nHhcNMTkwNTA5MTc0NzUyWhcNMjAwNTA4MTc0NzUyWjCBjjElMCMGCgmSJomT8ixk\r\nAQEMFWNvbS5xYW5kb3JhcHAucWFuZG9yMzFDMEEGA1UEAww6QXBwbGUgRGV2ZWxv\r\ncG1lbnQgSU9TIFB1c2ggU2VydmljZXM6IGNvbS5xYW5kb3JhcHAucWFuZG9yMzET\r\nMBEGA1UECwwKTlA2UE5GUUdBODELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEB\r\nAQUAA4IBDwAwggEKAoIBAQDIo+8GD6chbxCFDI7bTK6iTxQHnD/FiXJvEYBbO3ey\r\nQV8/XZm66VbO+RbA4UArA2bjdW5KZkSQ7hSYJcomQCmcmpqmrXjcaL0KfeWinSz4\r\nmbXxoXK9JsoUSjOfy7yXHGDLZSHGVvn5gO1FU9WPX3Iu7YYMT1hwnMgmZIuzn5K9\r\nAiyxvQzSlIlEsnpoqTDUz+1eXtPXAISPQT8+jM8JoZohTrODuUUj2rSPWi62kMBP\r\nsX4H4ncSjI56DG/E0lvUV7d0PEiUnoxGwzycmGJVgpZqv/E6p1eUNT7Utl4ktuiq\r\nEv8ft3+brJx+FokMi7AKjxLvlYS18LTG6JbQMcmXHsdlAgMBAAGjggHlMIIB4TAJ\r\nBgNVHRMEAjAAMB8GA1UdIwQYMBaAFIgnFwmpthhgi+zruvZHWcVSVKO3MIIBDwYD\r\nVR0gBIIBBjCCAQIwgf8GCSqGSIb3Y2QFATCB8TCBwwYIKwYBBQUHAgIwgbYMgbNS\r\nZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVz\r\nIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJt\r\ncyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQg\r\nY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjApBggrBgEFBQcCARYd\r\naHR0cDovL3d3dy5hcHBsZS5jb20vYXBwbGVjYS8wEwYDVR0lBAwwCgYIKwYBBQUH\r\nAwIwTQYDVR0fBEYwRDBCoECgPoY8aHR0cDovL2RldmVsb3Blci5hcHBsZS5jb20v\r\nY2VydGlmaWNhdGlvbmF1dGhvcml0eS93d2RyY2EuY3JsMB0GA1UdDgQWBBR6BPca\r\ngaRwijNzbL4lcYrJkU2r7TALBgNVHQ8EBAMCB4AwEAYKKoZIhvdjZAYDAQQCBQAw\r\nDQYJKoZIhvcNAQEFBQADggEBAFcIWIc1T0PtgeaMgjwQcTmfJGy8MUdIO/hdElo/\r\nOZF4ts4c2xkddanZ9IzOCj/HzmRJEs6WVZhNxySc3Cxo6KejsLbGLJmMoEh72xyQ\r\nwgnMBiapMnRhCfd68NMnTUClNHvGsg+NipnAN63r+HZSgPsCMXHsEMyZ+qQendRc\r\nDZH6m5FN1TqdAVtChdDPItzYJuQpyeKJpiiQGeCd6YjCELkWVxHcTU67CWmkuVqx\r\n9BRoANbJXty3b9T5KHxJYcEMj3pvsgcTOR/nGKIT9+B2iqrt6i/YY2n4p5NXXFzZ\r\nHewPc93srGXfyrvW7SeQs+93vZ7WlntfihY7WCoUbEOnHso=\r\n-----END CERTIFICATE-----"
  pushKey: "-----BEGIN RSA PRIVATE KEY-----\r\nMIIEpQIBAAKCAQEAyKPvBg+nIW8QhQyO20yuok8UB5w/xYlybxGAWzt3skFfP12Z\r\nuulWzvkWwOFAKwNm43VuSmZEkO4UmCXKJkApnJqapq143Gi9Cn3lop0s+Jm18aFy\r\nvSbKFEozn8u8lxxgy2Uhxlb5+YDtRVPVj19yLu2GDE9YcJzIJmSLs5+SvQIssb0M\r\n0pSJRLJ6aKkw1M/tXl7T1wCEj0E/PozPCaGaIU6zg7lFI9q0j1outpDAT7F+B+J3\r\nEoyOegxvxNJb1Fe3dDxIlJ6MRsM8nJhiVYKWar/xOqdXlDU+1LZeJLboqhL/H7d/\r\nm6ycfhaJDIuwCo8S75WEtfC0xuiW0DHJlx7HZQIDAQABAoIBAFNo+1xMs5FNp9N4\r\nBgebGFp3f38ucMCBRGZyIydKUJd1X9Bq7BbtHF6M5O2odtGq52IWFpStcUHDCCK8\r\nSw6dy+7DwxkZss4GaNhswENbDjAHTsE1+goyjv3iXxXGUA+OB5tm3qSi0ebstzcE\r\nBBtHdaOWsQx7C+w88WQslntFEm6qNSqeM1s5eQ20wSnlAA43Pm+NdVNM+JYX4iqt\r\n/MFdaPINE5XAXyBRAYir0l1dkofeGsb4rCuZmXSmjRRcC9vdhzmjrDUxLspOI7du\r\nUT7vYy3/hWFdng5oHu7JoDVrxF8/5e11j04jTq8SiHYfxUdR/Pmzt4/Nnu8SVjDJ\r\nesZJhwECgYEA7ElQyw2fzF3CQ2x526SBvLfFSxuX8zDkPjFtsrpZf78MHz9AR3ak\r\nlgEjR9aOfeWC1nRRZ6kGG8AgbpIZEN5KoCwZM98D6oub0VIg8iuR1UeArjebI8QV\r\nq2q5BeR3v2nmHsDXeG57D7O7DRko1tazp+d3/19hmMBOa4os19SsEaUCgYEA2WFH\r\nPtVwRtsQNcuKBCKHGzEVDG6Gm86kye2AdfJB7USr0fvD3HRah/chGi+foz+CDwwA\r\nzuBcgL45rSZZCTA9AFzihVpAFJ+a3GDgT/hSjJmMX3vHmySaZABmKNsiXRlPW+Fr\r\n7jkXwk7JH6emgcBH9d+Gyyp6ybVZvv/tNrFCcsECgYEA1DhtNlLASZ+UUVZmhF3W\r\noJc1vmXELgqllS5z5mj05YXD73Sx2P24iXnwJB+Sz4SJ5O+IBeCLufTvrB/QH5Rn\r\n1kCFSk9thwVpJ7HqIVf8nWChNNiAoLkG9XTfRWmUG/mTU9/EJ0ijgtDcmcEVKxCf\r\nP5jn8BfM4pMmW/Q4nolHGnkCgYEAnnLT1a8KSft/k1arYVwxktZx+z/NCmDTqQRf\r\nMJnHCEWX4FVdbKG7I4Q1Mrsn53xxNrqPFDxh8M23iMh8+b+Zl1wdGQqxztaPsLdE\r\nicX9ldKOiULWOfWyO9Y2oO0p3SaHu/dSDrC66r02yMYRDl6zlTq7K/fozIJNynUN\r\n2WHXh4ECgYEAneclaDj/KMtedyaJcblyEjtpzW3V/Gotws2cAaHqVaWDJHRrp0bl\r\nZNg8Jjf/NoixxENZ5bdduAR3JEjTwScRpOluO45Huq2gIMS7jsBKoDAvF94DNUI5\r\nNDtK8x/8+SOdk5HAGNHDoMqVbgZ2NpeOIGxzoZUCCK4f1j1CZbeEIio=\r\n-----END RSA PRIVATE KEY-----"
  bundleId: com.notused
  sandbox: true

unidentifiedDelivery:
  certificate: CiYI0gkSIQ000009AiF8PZMW0KzbjzRI8CviWkqU6CbkizpnlXRMqQVxJAhPaH0KYrIHUkCfoOmiysxpdbP0TnQWcPzzo3iXmN59fzESoalF/jmAJkULQWt3Pxv6Jz0c8O4qZ5KO77XPPcCA== # Your generated certificate
  privateKey: eI1uxnJlJ+n000009ybVniZnqOjZ/GuhRgw7/I8v4g0zHM= # Change this to you generated private key
  expiresDays: 365

voiceVerification: # voice otp verification, afaik it use vox service
  url: https://server.chatapp.net
  locales:
    - en

pushScheduler: # redis server for push scheduler
  url: redis://127.0.0.1:6379/pushScheduler # change to your redis server
  #replicaUrls:
  #  - redis://127.0.0.1:6379/pushSchedulerReplica # change to your redis server

server: # server configuration
  applicationConnectors:
    - type: http
      port: 8080 # your signal server will run on this port
  adminConnectors:
    - type: http
      port: 8081 # your signal server admin will run on this port
